from .colors import (
    NAVY, BLUE, CYAN, EMERALD, AMBER, CORAL, SLATE, GRAY, WHITE,
    GRADIENT_PRIMARY, GRADIENT_ACCENT, GRADIENT_SUCCESS,
    SENIORITY_COLORS,
)

__all__ = [
    "NAVY", "BLUE", "CYAN", "EMERALD", "AMBER", "CORAL",
    "SLATE", "GRAY", "WHITE",
    "GRADIENT_PRIMARY", "GRADIENT_ACCENT", "GRADIENT_SUCCESS",
    "SENIORITY_COLORS",
]
